Add Realm management
astarte-platform/astarte-client-elixir pull request #11
Opened 2022-03-25 16:34 UTC by szakhlypa

Adds `Astarte.Client.RealmManagement` to configure:
- RealmConfig
- Interfaces
- Triggers

2022-03-29 09:05 UTC, Pavinati commented on lib/astarte/client/realm_management/interfaces.ex
> +  def get_major_versions(%RealmManagement{} = client, interface_name)
should this be `list_major_versions`?

2022-03-29 15:45 UTC, rbino requested changes

2022-03-31 13:09 UTC, rbino commented on lib/astarte/client/realm_management/interfaces.ex
> +    with {:ok, %Tesla.Env{} = result} <- Tesla.post(tesla_client, request_path, %{data: data}) do
After some discussion, let's leave this as is this right now (i.e. just accept a map representing the interface)

2022-04-04 10:45 UTC, rbino approved these changes

2022-04-04 10:45 UTC, merged