Adds Housekeeping
astarte-platform/astarte-client-elixir pull request #7
Opened 2021-11-26 10:08 UTC by szakhlypa

2022-01-27 11:58 UTC, rbino requested changes

2022-01-27 11:58 UTC, rbino commented on lib/astarte/client/housekeeping/realms.ex
> +  end
I'd flatten all this with a `cond` to make it more readable:
```elixir
defp fetch_replication(opts) do
  cond do
    Keyword.has_key?(opts, :datacenter_replication_factors) ->
      replication = %{
        datacenter_replication_factors: Keyword.fetch!(opts, :datacenter_replication_factors),
        replication_class: "NetworkTopologyStrategy"
      }
      {:ok, replication}

    Keyword.has_key?(opts, :replication_factor) ->
      ...

    true ->
      {:error, :missing_replication}
  end
end
```

2022-01-27 11:58 UTC, rbino commented on lib/astarte/client/housekeeping/realms.ex
> +  end
also, `:missing_replication` is enough (your error is way too long imho) and also if you return `{:error, reason}` you have to wrap a correct result in an `{:ok, result}` tuple (which you weren't doing)

2022-02-14 15:49 UTC, rbino approved these changes

2022-02-14 15:54 UTC, bettio approved these changes

2022-02-14 15:54 UTC, merged